### ISSUE TITLE
Py3 migratie + lib update

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/static_map_generator#45]

**Comment by vancamti** [comment]
@roefem 
Bij deze zat ik vast, ik kreeg de testen lokaal niet echt in orde na de changes voor py3. Mijn changes staan op `feature/45_update_libs`
In python 2.7 environment had ik 1 falende test maar dat was wss gewoon een test die niet onderhouden was aangezien die testen ook al een tijdje falen op travis.
Volgens mij is het iets met die mapnik, daar had ik moeite mee om die in virtual environment te krijgen. Dat is uiteindelijk gelukt door: `sudo apt install python3-mapnik`  `import mapnik` en dan `python -m venv --system-site-packages mapnik .venv`. Dan had ik die mapnik==0.1 in mijn venv, maar kreeg ik op de testen: 
```
Error
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "<string>", line 3, in wrapper
  File "/home/timvc/PycharmProjects/static_map_generator/tests/test_views.py", line 64, in test_maps_by_post
    res = rest_view.maps_by_post_stream()
  File "/home/timvc/PycharmProjects/static_map_generator/static_map_generator/views/views.py", line 53, in maps_by_post_stream
    res.body = Generator.generate_stream(config)
  File "/home/timvc/PycharmProjects/static_map_generator/static_map_generator/generator.py", line 145, in generate_stream
    image_file = Generator.generate(config)
  File "/home/timvc/PycharmProjects/static_map_generator/static_map_generator/generator.py", line 67, in generate
    mapnik_map.zoom_all()
RuntimeError: Cannot initialize projection '+init=epsg:31370 ' without proj4 support (-DMAPNIK_USE_PROJ4)
```
Die error opzoeken kwam ik hier https://github.com/mapnik/mapnik-support/issues/17 terecht. Daar zeggen ze
> Right, the pre-built SDK does not use Proj4 and therefore does not support projections other than EPSG:4326 and EPSG:3857.
Maar dat vind ik ook maar vreemd want dat zou het me py2 ook niet echt gewerkt hebben, dus ik weet niet exact wat het probleem is...

**Comment by roefem** [comment]
Als ik de travis file bekijk zie ik dat mapnik voor py2 ook gebuild werd, zal je dan ook voor py3 moeten doen en zien dat proj4 support enabled is dan. Neem ik dat op?
